// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/asignacion.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AsignacionService_AsignarEmergencia_FullMethodName = "/asignacion.AsignacionService/AsignarEmergencia"
)

// AsignacionServiceClient is the client API for AsignacionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AsignacionServiceClient interface {
	AsignarEmergencia(ctx context.Context, in *EmergenciaRequest, opts ...grpc.CallOption) (*EmergenciaReply, error)
}

type asignacionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAsignacionServiceClient(cc grpc.ClientConnInterface) AsignacionServiceClient {
	return &asignacionServiceClient{cc}
}

func (c *asignacionServiceClient) AsignarEmergencia(ctx context.Context, in *EmergenciaRequest, opts ...grpc.CallOption) (*EmergenciaReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmergenciaReply)
	err := c.cc.Invoke(ctx, AsignacionService_AsignarEmergencia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AsignacionServiceServer is the server API for AsignacionService service.
// All implementations must embed UnimplementedAsignacionServiceServer
// for forward compatibility.
type AsignacionServiceServer interface {
	AsignarEmergencia(context.Context, *EmergenciaRequest) (*EmergenciaReply, error)
	mustEmbedUnimplementedAsignacionServiceServer()
}

// UnimplementedAsignacionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAsignacionServiceServer struct{}

func (UnimplementedAsignacionServiceServer) AsignarEmergencia(context.Context, *EmergenciaRequest) (*EmergenciaReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AsignarEmergencia not implemented")
}
func (UnimplementedAsignacionServiceServer) mustEmbedUnimplementedAsignacionServiceServer() {}
func (UnimplementedAsignacionServiceServer) testEmbeddedByValue()                           {}

// UnsafeAsignacionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AsignacionServiceServer will
// result in compilation errors.
type UnsafeAsignacionServiceServer interface {
	mustEmbedUnimplementedAsignacionServiceServer()
}

func RegisterAsignacionServiceServer(s grpc.ServiceRegistrar, srv AsignacionServiceServer) {
	// If the following call pancis, it indicates UnimplementedAsignacionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AsignacionService_ServiceDesc, srv)
}

func _AsignacionService_AsignarEmergencia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmergenciaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsignacionServiceServer).AsignarEmergencia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsignacionService_AsignarEmergencia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsignacionServiceServer).AsignarEmergencia(ctx, req.(*EmergenciaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AsignacionService_ServiceDesc is the grpc.ServiceDesc for AsignacionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AsignacionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "asignacion.AsignacionService",
	HandlerType: (*AsignacionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AsignarEmergencia",
			Handler:    _AsignacionService_AsignarEmergencia_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/asignacion.proto",
}
