// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/drones.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DroneRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DronId         string                 `protobuf:"bytes,1,opt,name=dronId,proto3" json:"dronId,omitempty"`
	Ubicacion      string                 `protobuf:"bytes,2,opt,name=ubicacion,proto3" json:"ubicacion,omitempty"`
	TipoEmergencia string                 `protobuf:"bytes,3,opt,name=tipoEmergencia,proto3" json:"tipoEmergencia,omitempty"`
	Latitude       float32                `protobuf:"fixed32,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude      float32                `protobuf:"fixed32,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Magnitud       int32                  `protobuf:"varint,6,opt,name=magnitud,proto3" json:"magnitud,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DroneRequest) Reset() {
	*x = DroneRequest{}
	mi := &file_proto_drones_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DroneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DroneRequest) ProtoMessage() {}

func (x *DroneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_drones_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DroneRequest.ProtoReflect.Descriptor instead.
func (*DroneRequest) Descriptor() ([]byte, []int) {
	return file_proto_drones_proto_rawDescGZIP(), []int{0}
}

func (x *DroneRequest) GetDronId() string {
	if x != nil {
		return x.DronId
	}
	return ""
}

func (x *DroneRequest) GetUbicacion() string {
	if x != nil {
		return x.Ubicacion
	}
	return ""
}

func (x *DroneRequest) GetTipoEmergencia() string {
	if x != nil {
		return x.TipoEmergencia
	}
	return ""
}

func (x *DroneRequest) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *DroneRequest) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *DroneRequest) GetMagnitud() int32 {
	if x != nil {
		return x.Magnitud
	}
	return 0
}

type DroneReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Estado        string                 `protobuf:"bytes,1,opt,name=estado,proto3" json:"estado,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DroneReply) Reset() {
	*x = DroneReply{}
	mi := &file_proto_drones_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DroneReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DroneReply) ProtoMessage() {}

func (x *DroneReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_drones_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DroneReply.ProtoReflect.Descriptor instead.
func (*DroneReply) Descriptor() ([]byte, []int) {
	return file_proto_drones_proto_rawDescGZIP(), []int{1}
}

func (x *DroneReply) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

var File_proto_drones_proto protoreflect.FileDescriptor

const file_proto_drones_proto_rawDesc = "" +
	"\n" +
	"\x12proto/drones.proto\x12\x06drones\"\xc2\x01\n" +
	"\fDroneRequest\x12\x16\n" +
	"\x06dronId\x18\x01 \x01(\tR\x06dronId\x12\x1c\n" +
	"\tubicacion\x18\x02 \x01(\tR\tubicacion\x12&\n" +
	"\x0etipoEmergencia\x18\x03 \x01(\tR\x0etipoEmergencia\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x02R\tlongitude\x12\x1a\n" +
	"\bmagnitud\x18\x06 \x01(\x05R\bmagnitud\"$\n" +
	"\n" +
	"DroneReply\x12\x16\n" +
	"\x06estado\x18\x01 \x01(\tR\x06estado2M\n" +
	"\fDroneService\x12=\n" +
	"\x11AtenderEmergencia\x12\x14.drones.DroneRequest\x1a\x12.drones.DroneReplyB\tZ\a./protob\x06proto3"

var (
	file_proto_drones_proto_rawDescOnce sync.Once
	file_proto_drones_proto_rawDescData []byte
)

func file_proto_drones_proto_rawDescGZIP() []byte {
	file_proto_drones_proto_rawDescOnce.Do(func() {
		file_proto_drones_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_drones_proto_rawDesc), len(file_proto_drones_proto_rawDesc)))
	})
	return file_proto_drones_proto_rawDescData
}

var file_proto_drones_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_drones_proto_goTypes = []any{
	(*DroneRequest)(nil), // 0: drones.DroneRequest
	(*DroneReply)(nil),   // 1: drones.DroneReply
}
var file_proto_drones_proto_depIdxs = []int32{
	0, // 0: drones.DroneService.AtenderEmergencia:input_type -> drones.DroneRequest
	1, // 1: drones.DroneService.AtenderEmergencia:output_type -> drones.DroneReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_drones_proto_init() }
func file_proto_drones_proto_init() {
	if File_proto_drones_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_drones_proto_rawDesc), len(file_proto_drones_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_drones_proto_goTypes,
		DependencyIndexes: file_proto_drones_proto_depIdxs,
		MessageInfos:      file_proto_drones_proto_msgTypes,
	}.Build()
	File_proto_drones_proto = out.File
	file_proto_drones_proto_goTypes = nil
	file_proto_drones_proto_depIdxs = nil
}
