// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/monitoreo.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MonitoreoService_RecibirActualizaciones_FullMethodName = "/monitoreo.MonitoreoService/RecibirActualizaciones"
)

// MonitoreoServiceClient is the client API for MonitoreoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MonitoreoServiceClient interface {
	RecibirActualizaciones(ctx context.Context, in *ActualizacionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ActualizacionReply], error)
}

type monitoreoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitoreoServiceClient(cc grpc.ClientConnInterface) MonitoreoServiceClient {
	return &monitoreoServiceClient{cc}
}

func (c *monitoreoServiceClient) RecibirActualizaciones(ctx context.Context, in *ActualizacionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ActualizacionReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MonitoreoService_ServiceDesc.Streams[0], MonitoreoService_RecibirActualizaciones_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ActualizacionRequest, ActualizacionReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MonitoreoService_RecibirActualizacionesClient = grpc.ServerStreamingClient[ActualizacionReply]

// MonitoreoServiceServer is the server API for MonitoreoService service.
// All implementations must embed UnimplementedMonitoreoServiceServer
// for forward compatibility.
type MonitoreoServiceServer interface {
	RecibirActualizaciones(*ActualizacionRequest, grpc.ServerStreamingServer[ActualizacionReply]) error
	mustEmbedUnimplementedMonitoreoServiceServer()
}

// UnimplementedMonitoreoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMonitoreoServiceServer struct{}

func (UnimplementedMonitoreoServiceServer) RecibirActualizaciones(*ActualizacionRequest, grpc.ServerStreamingServer[ActualizacionReply]) error {
	return status.Errorf(codes.Unimplemented, "method RecibirActualizaciones not implemented")
}
func (UnimplementedMonitoreoServiceServer) mustEmbedUnimplementedMonitoreoServiceServer() {}
func (UnimplementedMonitoreoServiceServer) testEmbeddedByValue()                          {}

// UnsafeMonitoreoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonitoreoServiceServer will
// result in compilation errors.
type UnsafeMonitoreoServiceServer interface {
	mustEmbedUnimplementedMonitoreoServiceServer()
}

func RegisterMonitoreoServiceServer(s grpc.ServiceRegistrar, srv MonitoreoServiceServer) {
	// If the following call pancis, it indicates UnimplementedMonitoreoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MonitoreoService_ServiceDesc, srv)
}

func _MonitoreoService_RecibirActualizaciones_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ActualizacionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MonitoreoServiceServer).RecibirActualizaciones(m, &grpc.GenericServerStream[ActualizacionRequest, ActualizacionReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MonitoreoService_RecibirActualizacionesServer = grpc.ServerStreamingServer[ActualizacionReply]

// MonitoreoService_ServiceDesc is the grpc.ServiceDesc for MonitoreoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MonitoreoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitoreo.MonitoreoService",
	HandlerType: (*MonitoreoServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RecibirActualizaciones",
			Handler:       _MonitoreoService_RecibirActualizaciones_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/monitoreo.proto",
}
